# Changes here will be overwritten by Copier
_commit: 1.5.2
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2024'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: griffe-docfx
project_description: Signatures for entire C# programs using docfx.
project_name: griffe-docfx
public_release: false
python_package_command_line_name: griffe-docfx
python_package_distribution_name: griffe-docfx
python_package_import_name: griffe_docfx
repository_name: griffe-docfx
repository_namespace: mkdocstrings
repository_provider: github.com

